version: '3.1'
services:
    #  api:
    #    container_name: api
    #    restart: always
    #    build: .
    #    profiles: ["test"]
    #    ports:
    #      - ${NODE_PORT}:${NODE_PORT}
    #    depends_on:
    #      - shop_db
    #    volumes:
    #      - .:/usr/src/app

    shop_db:
        image: postgres
        container_name: sh_postgres
        env_file:
            - .env
        ports:
            - ${PG_PORT}:5432
        volumes:
            - ./docker-volumes/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${PG_DB_NAME}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
